name: Build Mklink EXE

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 1. 下载你的代码
      uses: actions/checkout@v4

    - name: 2. 安装 .NET 8 环境
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: 3. 编译打包单文件 EXE
      # 去掉了 PublishTrimmed 参数，防止报错
      run: dotnet publish MklinkTool.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -o output

    - name: 4. 上传成品供下载
      uses: actions/upload-artifact@v4
      with:
        name: MklinkTool_Windows_EXE
        path: output/MklinkTool.exe
